group: bluezone
language: node_js
node_js:
  - '10'

notifications:
  email: false 
 
branches:
  only:
    - master
    - staging
   
install:
  - npm install  

script:
  - set |grep TRAVIS    

# after_failure: 
#   - exit -1 

before_deploy:
  # - wget https://s3.amazonaws.com/go-cli/releases/v6.12.4/cf-cli_amd64.deb -qO temp.deb && sudo dpkg -i temp.deb
  # - rm temp.deb
  # - cf login -a https://api.ng.bluemix.net -u apikey -p ${CF_API_KEY} -o "GBS Design" -s "Observr"
  # - cf install-plugin antifreeze -r CF-Community
  # - cf install-plugin autopilot -r CF-Community 

deploy:
  # - provider: script
  #   skip_cleanup: true
  #   script: NODE_ENV=production next build && cf zero-downtime-push observr -f manifest.production.yml
  #   on:
  #     branch: master
  # - provider: script
  #   skip_cleanup: true
  #   script: NODE_ENV=staging next build && cf zero-downtime-push observr-staging -f manifest.staging.yml
  #   on: 
  #     branch: staging